### PR TITLE
BDOG-1267: Remove Scala 2.11

### PR DESCRIPTION
**Pull request by IanMcShane**

### CODE REVIEW

**Comment by cjwebb** [comment]
This project doesn't appear to depend on Play?
Do we need to change anything?

**Comment by IanMcShane** [comment]
test please

**Comment by IanMcShane** [comment]
test this please

**Review by martinusnel — DISMISSED** [review]

**Comment by IanMcShane** [comment]
test this please

**Review by martinusnel — APPROVED** [review]

**Pull request merged**
